language: python
python:
  - "3.3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=`pwd`
# command to run tests
script: 

  - nosetests --with-coverage --cover-package=SendITapp
after_success:
  - coverallslanguage: python
- coveralls