language: python
python:
 - "3.5.2"
# command to install dependencies
install:
 - pip install -r requirements.txt
 -pip install nose
 - pip install coveralls
 -pip install coverage
 
before_script:
 - export PYTHONPATH=`pwd`
# command to run tests
script: 
 - nosetests --with-coverage
after_success:
 - coverallslanguage: python
 - coveralls
